

; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Auftragsverwaltung"
#define MyAppVersion "1.5"
#define MyAppPublisher "BFW OHG"
#define MyAppURL "http://www.bfwka.de"
#define MyAppExeName "Auftragsverwaltungvcl"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B3648087-BED2-4836-9283-735E52610C5A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setup{#MyAppVersion}
Compression=lzma
SolidCompression=yes
OutputDir=H:\Melanie\setup\Auftragsverwaltung

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]                 
Source: c:\repositories\Auftragsverwaltung\Win32\Release\auftragsverwaltungvcl.exe; DestDir: {app}; Flags: ignoreversion
Source:c:\repositories\Auftragsverwaltung\Win32\Release\libmysql.dll; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Auftragsverwaltung\Win32\Release\sqlite3.dll; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Auftragsverwaltung\Win32\Release\doppelstart.dcu; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Auftragsverwaltung\Win32\Release\plink.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\Users\jovani\Documents\Embarcadero\Studio\Projekte\namepipeserver\Win32\Debug\pnamepipeserver.exe; DestDir: {app}; Flags: ignoreversion
Source:c:\repositories\Auftragsverwaltung\Win32\Release\plinkini.bat; DestDir: {app}; Flags: ignoreversion deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: aenderung.txt; DestDir: {commonappdata}; DestName: Auftragsverwaltung/aenderung.txt

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent
Filename: {app}\plinkini.bat; WorkingDir: {app}; Flags: shellexec runhidden



